name: Update CODEOWNERS
on:   
  pull_request:
    branches: [ main, develop, feature/* ]
jobs:
  update-codeowners:
    runs-on: ubuntu-20.04
    name: Update CODEOWNERS
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Renovate Merge
      # You may pin to the exact commit or the version.
      # uses: MansaGroup/renovate-merge-action@8163f611660c7587420001984ad4b64361a9679c
        uses: MansaGroup/renovate-merge-action@v0
        with:
        # The GitHub token used to create an authenticated client
          githubToken: ${{ github.BHARATH_SECRET }}
