name: Update CODEOWNERS
on:   
  pull_request:
    branches: [ main, develop, feature/* ]
jobs:
  update-codeowners:
    runs-on: ubuntu-20.04
    name: Update CODEOWNERS
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update CODEOWNERS file
        uses: mszostok/codeowners-validator@v0.7.4
        with:
          checks: "files,owners,duppatterns,syntax"
          experimental_checks: "notowned,avoid-shadowing"
            # GitHub access token is required only if the `owners` check is enabled
          github_access_token: "${{ secrets.BHARATH_SECRET }}"
